"use client";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowUpRight, Check, Clock3, MapPin, Menu, Scissors, Sparkles, UserRound, MessageCircle, Camera, Armchair, X, Quote } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Sheet, SheetContent, SheetDescription, SheetTitle, SheetTrigger, SheetClose } from "@/components/ui/sheet";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { site, services, gallery, team, questions, whatsappUrl, mapsUrl, mapEmbedUrl } from "@/content/site";
const navigation = [{ label: "Início", id: "inicio" }, { label: "Serviços", id: "servicos" }, { label: "Sobre", id: "sobre" }, { label: "Galeria", id: "galeria" }, { label: "Avaliações", id: "avaliacoes" }, { label: "Localização", id: "localizacao" }];
function Brand() { return <a href="#inicio" className="brand" aria-label={`${site.name} — início`}><span className="brand-symbol" aria-hidden="true">M</span><span className="brand-words"><span>BARBEARIA DO</span><strong>MARQUINHOS</strong></span></a>; }
function Booking({ children = "Agendar horário", service, className = "" }: { children?: React.ReactNode; service?: string; className?: string }) { return <a href={whatsappUrl(service)} target="_blank" rel="noopener noreferrer" className={`button button-gold ${className}`} aria-label={service ? `Agendar ${service} pelo WhatsApp` : "Agendar horário pelo WhatsApp"}><MessageCircle size={18} aria-hidden="true" />{children}<ArrowUpRight size={18} aria-hidden="true" /></a>; }
export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [selectedPhoto, setSelectedPhoto] = useState<number | null>(null);
  const [active, setActive] = useState("inicio");
  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const observer = new IntersectionObserver(entries => { entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }); }, { threshold: 0.05 });
    document.querySelectorAll(".reveal").forEach(el => { el.classList.add("will-reveal"); observer.observe(el); });
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const observer = new IntersectionObserver(entries => { entries.forEach(entry => { if (entry.isIntersecting) setActive(entry.target.id); }); }, { rootMargin: "-18% 0px -65% 0px", threshold: 0 });
    navigation.forEach(item => { const el = document.getElementById(item.id); if (el) observer.observe(el); });
    const query = window.matchMedia("(min-width: 1101px)"); const close = () => { if (query.matches) setMenuOpen(false); }; query.addEventListener("change", close);
    return () => { observer.disconnect(); query.removeEventListener("change", close); };
  }, []);
  return <>
    <a className="skip-link" href="#conteudo">Pular para o conteúdo</a>
    {site.draft && <div className="draft-bar"><span>PROPOSTA INICIAL</span><p>Fotos ilustrativas · informações em revisão</p></div>}
    <header className="site-header"><div className="container header-inner"><Brand /><nav className="desktop-nav" aria-label="Navegação principal">{navigation.map(item => <a key={item.id} href={`#${item.id}`} className={active === item.id ? "is-active" : ""} aria-current={active === item.id ? "location" : undefined}>{item.label}</a>)}</nav><Booking className="header-booking" />
      <Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetTrigger asChild><button className="mobile-toggle" aria-label="Abrir menu" aria-expanded={menuOpen}><Menu size={26} /></button></SheetTrigger><SheetContent className="mobile-menu" showCloseButton={false}><SheetTitle className="mobile-menu-title">Barbearia do Marquinhos</SheetTitle><SheetDescription className="sr-only">Navegue pelas seções ou agende pelo WhatsApp.</SheetDescription><SheetClose asChild><button className="menu-close" aria-label="Fechar menu"><X size={24} /></button></SheetClose><span className="eyebrow">SEU ESTILO COMEÇA AQUI</span><nav aria-label="Navegação no celular">{navigation.map((item, i) => <a key={item.id} href={`#${item.id}`} onClick={() => setMenuOpen(false)}><span>0{i + 1}</span>{item.label}<ArrowUpRight size={20} /></a>)}</nav><Booking /><p className="mobile-menu-address">{site.address.street}<br />Centro · {site.city}</p></SheetContent></Sheet>
    </div></header>
    <main id="conteudo">
      <section id="inicio" className="hero" aria-labelledby="hero-title"><img className="hero-photo" src={site.images.hero.src} alt={site.images.hero.alt} width="1920" height="1282" fetchPriority="high" /><div className="hero-shade" /><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow"><span className="short-rule" /> BARBEARIA DO MARQUINHOS · INDAIATUBA</p><h1 id="hero-title">UM BOM CORTE.<br />UMA NOVA<br /><em>ATITUDE.</em></h1><p className="hero-description">Mais que um corte, o seu jeito de se apresentar.<br className="desktop-break" /> Encontre seu próximo estilo no centro de Indaiatuba.</p><div className="hero-actions"><Booking /><a className="text-link" href="#servicos">Conhecer serviços <ArrowDown size={17} /></a></div><p className="hero-footnote"><Check size={14} /> Simples, direto pelo WhatsApp.</p></div><div className="hero-photo-label"><span>01 / ESTILO EM CADA DETALHE</span><span>FOTO ILUSTRATIVA</span></div><a className="scroll-cue" href="#servicos" aria-label="Rolar para serviços"><ArrowDown size={22} /></a></div></section>
      <div className="info-strip"><div className="container info-strip-inner"><a href={mapsUrl()} target="_blank" rel="noopener noreferrer"><MapPin /><span>NO CENTRO DE INDAIATUBA<small>{site.address.street}</small></span></a><div><Clock3 /><span>O SEU MOMENTO, NA SUA ROTINA<small>Ter–Sex: 08h–19h · Sáb: 08h–18h</small></span></div><a href="#servicos" className="strip-specialty"><Scissors /><span>CORTE, BARBA & PERSONALIDADE<small>Um cuidado que combina com você</small></span></a></div></div>
      <section id="servicos" className="section services-section" aria-labelledby="services-title"><div className="container"><div className="section-heading reveal"><div><p className="eyebrow">01 — NOSSOS SERVIÇOS</p><h2 id="services-title">NA MEDIDA DO<br /><span>SEU ESTILO.</span></h2></div><p>Do acabamento ao visual completo.<br />Escolha seu serviço e combine um horário.</p></div><div className="service-grid">{services.map((service, i) => <article className={`service-card reveal ${service.featured ? "featured" : ""}`} key={service.name}><div className="service-top"><span>0{i + 1}</span>{service.featured ? <span className="service-tag">COMPLETO</span> : <Scissors size={24} strokeWidth={1.3} />}</div><h3>{service.name}</h3><p>{service.description}</p><div className="service-bottom">{site.showPrices && <div className="service-price">{service.price}<span>valor a confirmar</span></div>}<a className="service-book" href={whatsappUrl(service.name)} target="_blank" rel="noopener noreferrer" aria-label={`Agendar ${service.name} pelo WhatsApp`}>Agendar<ArrowUpRight size={20} /></a></div></article>)}</div><p className="section-note">Serviços propostos e preços ilustrativos. Confirme valores e disponibilidade pelo WhatsApp.</p></div></section>
      <section id="sobre" className="section about-section" aria-labelledby="about-title"><div className="container"><div className="about-grid"><figure className="about-photo reveal"><img src={site.images.about.src} alt={site.images.about.alt} loading="lazy" width="900" height="1100" /><figcaption>UM ESPAÇO PARA O SEU ESTILO<span>Imagem ilustrativa</span></figcaption><span className="photo-corner" aria-hidden="true" /></figure><div className="about-copy reveal"><p className="eyebrow">02 — A BARBEARIA</p><h2 id="about-title">BOM PAPO.<br />BOM CORTE.<br /><span>DO SEU JEITO.</span></h2><p>{site.about.text}</p><p>{site.about.secondParagraph}</p><div className="about-signature"><span className="signature">Marquinhos</span><span>BARBEARIA · INDAIATUBA</span></div><a href="#localizacao" className="text-link gold-link">Venha conhecer <ArrowUpRight size={18} /></a></div></div><div className="values-grid reveal">{[{ icon: UserRound, title: "Seu estilo em primeiro lugar", text: "Uma conversa sobre o visual que você quer." }, { icon: Armchair, title: "Um tempo para você", text: "Uma pausa na rotina para cuidar do seu visual." }, { icon: Sparkles, title: "Atenção aos detalhes", text: "Do corte ao acabamento, cada detalhe faz parte." }, { icon: MessageCircle, title: "Agendamento simples", text: "Fale pelo WhatsApp e combine seu horário." }].map(({ icon: Icon, title, text }) => <div key={title}><Icon size={27} strokeWidth={1.4} /><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
      <section id="galeria" className="section gallery-section" aria-labelledby="gallery-title"><div className="container"><div className="section-heading reveal"><div><p className="eyebrow">03 — GALERIA</p><h2 id="gallery-title">O ESTILO FALA<br /><span>POR SI.</span></h2></div><p>Uma referência do que pode entrar por aqui.<br />Fotos reais da barbearia serão incluídas depois.</p></div><div className="gallery-grid">{gallery.map((photo, i) => <button type="button" className={`gallery-photo gallery-photo-${i} reveal`} key={photo.src} onClick={() => setSelectedPhoto(i)} aria-label={`Ampliar imagem ilustrativa: ${photo.title}`}><img src={photo.src} alt={photo.alt} loading="lazy" width="700" height="900" /><span className="gallery-overlay"><span><small>IMAGEM DE REFERÊNCIA</small><strong>{photo.title}</strong></span><ArrowUpRight size={24} /></span></button>)}</div><p className="section-note">Imagens ilustrativas; não representam trabalhos realizados ou o ambiente real da barbearia.</p></div></section>
      {site.showTeam && <section id="equipe" className="section team-section" aria-labelledby="team-title"><div className="container"><div className="section-heading reveal"><div><p className="eyebrow">04 — QUEM CUIDA DO SEU VISUAL</p><h2 id="team-title">GENTE QUE FAZ<br /><span>A DIFERENÇA.</span></h2></div><p>Um espaço para apresentar a equipe.<br />Nomes, fotos e informações a confirmar.</p></div><div className="team-grid">{team.map((name, i) => <article key={name} className="team-card reveal"><div className="team-placeholder"><UserRound size={56} strokeWidth={1} aria-hidden="true" /><span>FOTO A INCLUIR</span><b aria-hidden="true">0{i + 1}</b></div><div className="team-caption"><h3>{name}</h3><p>Nome e apresentação a incluir</p></div></article>)}</div></div></section>}
      <section id="avaliacoes" className="section reviews-section" aria-labelledby="reviews-title"><div className="container"><div className="section-heading reveal"><div><p className="eyebrow">05 — A PALAVRA É DE VOCÊS</p><h2 id="reviews-title">BOAS HISTÓRIAS<br /><span>COMEÇAM AQUI.</span></h2></div><p>Este espaço receberá avaliações reais.<br />Os cartões abaixo são demonstrativos.</p></div><div className="review-grid">{[1, 2, 3].map(n => <article key={n} className="review-card reveal"><div className="review-top"><Quote size={29} strokeWidth={1.4} /><span>EXEMPLO DE EXIBIÇÃO</span></div><blockquote>[Avaliação real do cliente será inserida aqui]</blockquote><div className="review-author"><span aria-hidden="true"><UserRound size={19} /></span><div><strong>[Nome do cliente]</strong><small>Depoimento a incluir</small></div></div></article>)}</div></div></section>
      <section id="localizacao" className="section location-section" aria-labelledby="location-title"><div className="container location-grid"><div className="location-copy reveal"><p className="eyebrow">06 — ONDE ESTAMOS</p><h2 id="location-title">SEU PRÓXIMO CORTE.<br /><span>BEM AQUI.</span></h2><div className="location-detail"><MapPin size={23} /><div><h3>NO CENTRO DE INDAIATUBA</h3><address>{site.address.street} — {site.address.neighborhood}<br />{site.city} — {site.address.state}, {site.address.postalCode}</address></div></div><div className="location-detail"><Clock3 size={23} /><div><h3>HORÁRIO DE FUNCIONAMENTO</h3><dl className="hours-list">{site.hours.map(row => <div key={row.days}><dt>{row.days}</dt><dd>{row.time}</dd></div>)}</dl></div></div><div className="location-actions"><a className="button button-outline" href={mapsUrl()} target="_blank" rel="noopener noreferrer">Ver no Google Maps<ArrowUpRight size={18} /></a><Booking>Falar no WhatsApp</Booking></div></div><div className="map-card reveal"><iframe title="Mapa do endereço informado da Barbearia do Marquinhos em Indaiatuba" src={mapEmbedUrl()} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen /><div className="map-caption"><MapPin size={24} /><div><strong>{site.name}</strong><span>{site.address.street} · Centro</span></div><a href={mapsUrl()} target="_blank" rel="noopener noreferrer" aria-label="Abrir endereço no Google Maps"><ArrowUpRight size={23} /></a></div></div></div></section>
      <section className="section faq-section" aria-labelledby="faq-title"><div className="container faq-grid"><div className="reveal"><p className="eyebrow">ANTES DE CHEGAR</p><h2 id="faq-title">FICOU COM<br /><span>ALGUMA DÚVIDA?</span></h2><p>Chama no WhatsApp.<br />A gente combina os próximos detalhes.</p><a className="text-link gold-link" href={whatsappUrl()} target="_blank" rel="noopener noreferrer">Conversar com a barbearia <ArrowUpRight size={18} /></a></div><Accordion type="single" collapsible className="faq-list reveal">{questions.map((question, i) => <AccordionItem value={`faq-${i}`} key={question.question}><AccordionTrigger className="faq-trigger">{question.question}</AccordionTrigger><AccordionContent className="faq-answer">{question.answer}{question.pending && <span className="pending-label">Informação a confirmar com a barbearia</span>}</AccordionContent></AccordionItem>)}</Accordion></div></section>
      <section className="closing-cta"><div className="container"><div><p className="eyebrow">BORA RENOVAR O VISUAL?</p><h2>O PRÓXIMO ESTILO<br />PODE SER O SEU.</h2></div><div><Booking /><p>Uma mensagem. Um horário. Seu novo visual.</p></div><Scissors className="closing-icon" strokeWidth={0.7} aria-hidden="true" /></div></section>
    </main>
    <footer className="site-footer"><div className="container"><div className="footer-main"><div className="footer-brand"><Brand /><p>Corte, barba e personalidade.<br />No centro de Indaiatuba.</p></div><div><h3>VENHA NOS VISITAR</h3><a href={mapsUrl()} target="_blank" rel="noopener noreferrer">{site.address.street} — Centro<br />{site.city} — SP<br />CEP {site.address.postalCode}</a></div><div><h3>QUANDO CHEGAR</h3><p>Terça a sexta: 08h às 19h<br />Sábado: 08h às 18h<br />Domingo e segunda: fechado</p></div><div><h3>VAMOS CONVERSAR</h3><a className="footer-contact" href={whatsappUrl()} target="_blank" rel="noopener noreferrer"><MessageCircle size={17} />{site.phoneDisplay}</a>{site.instagramUrl ? <a className="footer-contact" href={site.instagramUrl} target="_blank" rel="noopener noreferrer"><Camera size={17} />{site.instagramLabel}</a> : <span className="footer-contact instagram-placeholder"><Camera size={17} />Instagram a informar</span>}</div></div><div className="footer-bottom"><p>© {site.copyrightYear} {site.name}. Todos os direitos reservados.</p><span>PROTÓTIPO PARA APRESENTAÇÃO</span><a href="#inicio">Voltar ao topo <ArrowUpRight size={16} /></a></div></div></footer>
    <a className="floating-whatsapp" href={whatsappUrl()} target="_blank" rel="noopener noreferrer" aria-label="Conversar no WhatsApp com a Barbearia do Marquinhos"><MessageCircle size={28} strokeWidth={1.8} /><span>Vamos agendar?</span></a>
    <Dialog open={selectedPhoto !== null} onOpenChange={open => { if (!open) setSelectedPhoto(null); }}><DialogContent className="gallery-dialog">{selectedPhoto !== null && <><DialogTitle>{gallery[selectedPhoto].title}</DialogTitle><DialogDescription>Imagem ilustrativa. A foto real da barbearia será inserida após aprovação.</DialogDescription><img src={gallery[selectedPhoto].src} alt={gallery[selectedPhoto].alt} /></>}</DialogContent></Dialog>
  </>;
}
